# Generated by Django 5.0.3 on 2024-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PC', 'Paper Craft'), ('HD', 'Home decor'), ('DD', 'Diyas'), ('LI', 'Lighting'), ('SK', 'Sketch'), ('CA', 'Clay art'), ('HM', 'Handicraft')], max_length=2),
        ),
    ]
